# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Titel
description: ""
author: "Stefan Wendhausen"
baseurl: ""
url: "http://privacy-policy-suite.kicktemp.com"
googleanalyticss:

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME, .idea, .git]
sass:
  sass_dir: _sass
  style: compressed

repository: kicktemp/privacy-policy-suite